# Generated by Django 5.2.1 on 2025-05-11 05:32

from django.db import migrations, models
import datetime


def create_dummy_diskon(apps, schema_editor):
    Diskon = apps.get_model('diskon', 'diskon')
    Diskon.objects.create(
        code="DUMMY10",
        tipe_diskon="persen",
        value=10,
        expires_at=datetime.date(2025, 12, 31)
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diskon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
                ('min_transaksi', models.IntegerField()),
                ('expires_at', models.DateField()),
            ],
        ),
        migrations.RunPython(create_dummy_diskon),
    ]
