# Generated by Django 5.2.1 on 2025-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diskon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('tipe_diskon', models.CharField(choices=[('persen', 'Persen'), ('cashback', 'Cashback')], default='persen', max_length=10)),
                ('value', models.IntegerField()),
                ('min_transaksi', models.IntegerField()),
                ('expires_at', models.DateField()),
            ],
        ),
    ]
