# Generated by Django 5.2.1 on 2025-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskon',
            name='tipe_diskon',
            field=models.CharField(choices=[('persen', 'Persen'), ('cashback', 'Cashback')], default='persen', max_length=10),
        ),
    ]
