# Generated by Django 5.2.1 on 2025-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskon', '0002_diskon_tipe_diskon'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskon',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
