# Generated by Django 5.2.1 on 2025-05-13 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_rename_trip_id_rencanaperjalanan_trip'),
        ('trip_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmember',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trip.trip'),
        ),
    ]
