# Generated by Django 5.2.1 on 2025-05-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0004_remove_rencanaperjalanan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengingat',
            fields=[
                ('pengingat_id', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_pengingat', models.DateField()),
                ('is_sent', models.BooleanField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
    ]
