# Generated by Django 5.2.1 on 2025-05-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0004_remove_rencanaperjalanan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanPengeluaran',
            fields=[
                ('laporan_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_biaya', models.IntegerField()),
                ('biaya_per_orang', models.IntegerField()),
                ('rencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.rencanaperjalanan')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
    ]
