# Generated by Django 5.2.1 on 2025-05-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rencanaperjalanan',
            old_name='trip_id',
            new_name='trip',
        ),
    ]
