# Generated by Django 5.2.1 on 2025-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_rencanaperjalanan_jumlah_kamar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rencanaperjalanan',
            name='id',
        ),
        migrations.AddField(
            model_name='rencanaperjalanan',
            name='rencana_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
