name: Build and Push to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/tripzy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build & Push backend images
        run: |
          docker build -t $IMAGE_NAME:backend -t $IMAGE_NAME:backend-${{ steps.vars.outputs.sha_short }} ./backend
          docker push $IMAGE_NAME:backend
          docker push $IMAGE_NAME:backend-${{ steps.vars.outputs.sha_short }}

      - name: Build & Push frontend images
        run: |
          docker build -t $IMAGE_NAME:frontend -t $IMAGE_NAME:frontend-${{ steps.vars.outputs.sha_short }} ./frontend
          docker push $IMAGE_NAME:frontend
          docker push $IMAGE_NAME:frontend-${{ steps.vars.outputs.sha_short }}
